/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package windows;

import javax.swing.JOptionPane;

/**
 *
 * @author Jesús
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSearchClientMain = new javax.swing.JButton();
        btnSearchReservationMain = new javax.swing.JButton();
        btnHistoryRoomMain = new javax.swing.JButton();
        btnCheckinMain = new javax.swing.JButton();
        btnCheckoutMain = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnExitMain = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú Principal");
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(575, 450));
        setPreferredSize(new java.awt.Dimension(575, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, -1, -1));

        btnSearchClientMain.setText("Buscar clientes");
        btnSearchClientMain.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearchClientMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchClientMainActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearchClientMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 170, 30));

        btnSearchReservationMain.setText("Busqueda Reservación");
        btnSearchReservationMain.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearchReservationMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchReservationMainActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearchReservationMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 170, 30));

        btnHistoryRoomMain.setText("Historial de Habitaciones");
        btnHistoryRoomMain.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHistoryRoomMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoryRoomMainActionPerformed(evt);
            }
        });
        getContentPane().add(btnHistoryRoomMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 170, 30));

        btnCheckinMain.setText("Check-in");
        btnCheckinMain.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCheckinMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckinMainActionPerformed(evt);
            }
        });
        getContentPane().add(btnCheckinMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 170, 30));

        btnCheckoutMain.setText("Check-out");
        btnCheckoutMain.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCheckoutMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckoutMainActionPerformed(evt);
            }
        });
        getContentPane().add(btnCheckoutMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 170, 30));

        jButton1.setText("Importar Excel");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 170, 30));

        btnExitMain.setBackground(new java.awt.Color(153, 255, 255));
        btnExitMain.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExitMain.setText("X");
        btnExitMain.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnExitMain.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExitMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitMainActionPerformed(evt);
            }
        });
        getContentPane().add(btnExitMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 50, 30));

        jPanel2.setBackground(new java.awt.Color(51, 204, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Swis721 BlkEx BT", 0, 12)); // NOI18N
        jLabel2.setText("Programa Hotel Booking");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 250, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 30));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 570, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchReservationMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchReservationMainActionPerformed
       SearchStatus vtna = new SearchStatus();
        vtna.show();
        this.dispose();
    }//GEN-LAST:event_btnSearchReservationMainActionPerformed

    private void btnCheckoutMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckoutMainActionPerformed
        CheckOut vtna = new CheckOut();
        vtna.show();
        this.dispose();
    }//GEN-LAST:event_btnCheckoutMainActionPerformed

    private void btnSearchClientMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchClientMainActionPerformed
        
        SearchReservation vtna = new SearchReservation();
        vtna.show();
        this.dispose();
    }//GEN-LAST:event_btnSearchClientMainActionPerformed

    private void btnHistoryRoomMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoryRoomMainActionPerformed
        HistoryRoom vtna = new HistoryRoom();
        vtna.show();
        this.dispose();
    }//GEN-LAST:event_btnHistoryRoomMainActionPerformed

    private void btnCheckinMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckinMainActionPerformed
        Checkin vtna = new Checkin();
        vtna.show();
        this.dispose();
    }//GEN-LAST:event_btnCheckinMainActionPerformed

    private void btnExitMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitMainActionPerformed
        this.dispose();
        JOptionPane.showMessageDialog(null, "Ha cerrado el programa.", "Finalizado", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnExitMainActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheckinMain;
    private javax.swing.JButton btnCheckoutMain;
    private javax.swing.JButton btnExitMain;
    private javax.swing.JButton btnHistoryRoomMain;
    private javax.swing.JButton btnSearchClientMain;
    private javax.swing.JButton btnSearchReservationMain;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
